### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [JekaIvaschenko/grid-template-init-project#1]
1)
внешний вид не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/101337769-c1037580-3884-11eb-980b-23cca7934757.png)

2)
требования к высоте не выполнены
3)
текст отображается некорректно
![image](https://user-images.githubusercontent.com/8464662/101337871-e1333480-3884-11eb-85ac-723fad7058de.png)

**Comment by JekaIvaschenko** [comment]
2,3 сделал
1 не понял в чем проблема? все так же отображается как в xd так и на оф сайте

**Comment by JekaIvaschenko** [comment]
все , решил

**Comment by Alecto** [comment]
2 ссылочки можно?
у меня их сейчас нет

вт, 8 груд. 2020 о 00:59 JekaIvaschenko <notifications@github.com> пише:
